#!/bin/bash
# MasterCoderAI - Quick Start Guide

echo "🚀 MasterCoderAI - QUICK START"
echo "=============================="
echo ""
echo "1️⃣ START EVERYTHING:"
echo "   ./run_all.sh"
echo ""
echo "2️⃣ ACCESS:"
echo "   http://$(hostname -I | awk '{print $1}'):3000"
echo ""
echo "3️⃣ LOGIN:"
echo "   Username: admin"
echo "   Password: admin"
echo ""
echo "4️⃣ LOAD MODEL:"
echo "   Go to Models tab → Click 'Load' on any model"
echo ""
echo "5️⃣ CHAT:"
echo "   Type message in Chat tab and send"
echo ""
echo "6️⃣ IMAGE UPLOAD:"
echo "   Click 📷 button → select image → AI will read text (OCR)"
echo ""
echo "7️⃣ IMAGE GENERATION:"
echo "   Check '🎨 Generate Image' → describe image → AI explains"
echo ""
echo "📝 LOGS:"
echo "   Backend:  tail -f /tmp/backend.log"
echo "   Frontend: tail -f /tmp/frontend.log"
echo ""
echo "🛑 STOP:"
echo "   ./stop.sh"
echo ""
echo "✅ DONE! All features ready to use."
