#!/bin/bash

echo "========================================="
echo "🔥 INCOGNITO MODE - KAKO TESTIRATI"
echo "========================================="
echo ""
echo "PROBLEM: Incognito ne koristi cache ALI možda učita STARI JS file!"
echo ""
echo "========================================="
echo "✅ RJEŠENJE - URADI OVO:"
echo "========================================="
echo ""
echo "1. Zatvori SVE incognito tabove"
echo ""
echo "2. Otvori NOVI incognito tab"
echo ""
echo "3. Idi na: http://localhost:8000"
echo ""
echo "4. Login: admin / admin123"
echo ""
echo "5. Pritisni F12 (Developer Tools)"
echo ""
echo "6. Idi u Network tab"
echo ""
echo "7. Refreshuj stranicu (F5)"
echo ""
echo "8. Traži main.*.js file i provjeri:"
echo "   - Timestamp: Treba biti $(date '+%H:%M')"
echo "   - Size: Treba biti ~275KB"
echo ""
echo "9. Ako vidiš STARI timestamp:"
echo "   - Ctrl + F5 (force reload)"
echo "   - Ili zatvori browser KOMPLETNO i otvori ponovo"
echo ""
echo "========================================="
echo "🧪 KAKO TESTIRATI BUTTONE:"
echo "========================================="
echo ""
echo "A) SAVE AI SETTINGS:"
echo "   1. Settings tab"
echo "   2. Promijeni Temperature"
echo "   3. Klikni 💾 SAVE AI Settings"
echo "   4. OČEKIVANO: Alert '✅ AI Settings saved successfully!'"
echo ""
echo "B) DELETE CHAT:"
echo "   1. Chat tab (ako si admin)"
echo "   2. U sidebar-u vidi chat listu"
echo "   3. Klikni 🗑️ na nekom chatu"
echo "   4. OČEKIVANO:"
echo "      - Confirm dialog"
echo "      - Alert '✅ Chat deleted!'"
echo ""
echo "C) CLEAR ALL:"
echo "   1. Klikni 🗑️ ALL button"
echo "   2. OČEKIVANO:"
echo "      - 2x confirm dialog"
echo "      - Alert '✅ All chats deleted!'"
echo ""
echo "D) DOWNLOAD CHAT:"
echo "   1. Klikni 💾 button"
echo "   2. OČEKIVANO:"
echo "      - Download .txt file"
echo "      - Alert '✅ Chat downloaded successfully!'"
echo ""
echo "========================================="
echo "❌ AKO NE RADI - PROVJERI OVO:"
echo "========================================="
echo ""
echo "1. F12 Console - Ima li ERRORA?"
echo "   - Ako vidiš error, kopiraj ga i pošalji mi"
echo ""
echo "2. F12 Network tab:"
echo "   - Kad klikneš button, vidiš li API request?"
echo "   - Koji je status code? (200 = OK, 422/500 = ERROR)"
echo ""
echo "3. Backend log:"
tail -20 /tmp/backend.log
echo ""
echo "========================================="
echo "📊 TRENUTNI STATUS:"
echo "========================================="
echo ""
echo "✅ Backend: RUNNING (port 8000)"
echo "✅ Frontend Build: $(date -r /root/MasterCoderAI/frontend/build/static/js/main.*.js '+%H:%M:%S')"
echo "✅ API Endpoints: ALL WORKING (tested above)"
echo ""
echo "🔥 PROBLEM JE BROWSER CACHE!"
echo ""
echo "URADI:"
echo "1. Zatvori CIJELI browser (ne samo tab)"
echo "2. Otvori ponovo"
echo "3. Incognito mode"
echo "4. http://localhost:8000"
echo "5. F12 Network tab - provjeri main.*.js timestamp"
echo ""
echo "========================================="
